# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install requests
            pipenv install pytest
          
      - run:
          name: launch todoserver.py
          command: |
            pipenv run python todoserver.py
          background: true

      - run: 
          name: run test_server.py
          command: |
            pytest
